### ISSUE TITLE
Lock violation on path /sys/class/gpio/export

### ISSUE THREAD

**Issue by ninjaboy** [AlexSartori/Raspberry-GPIO-Manager#1]
System.IO.Exception when trying to set Status

**Comment by AlexSartori** [comment]
Hi ninjaboy, thanks for the issue. One thing: are you sure you have root permissions?

**Comment by ninjaboy** [comment]
Hi Alex

Yes I do sudo when run the app. Everything works fine
with raspberry-sharp/raspberry-sharp-io library.

On Wed, Mar 25, 2015 at 7:23 PM, Alex notifications@github.com wrote:

> Hi ninjaboy, thank for the issue. One thing: are you sure to have root
> permissions?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexSartori/Raspberry-GPIO-Manager/issues/1#issuecomment-86181122
> .

## 

With best regards,
_Alexey Stolybko_

**Comment by AlexSartori** [comment]
Ok thank you very much. I will now try to figure it out and update the library.

**Comment by AlexSartori** [comment]
It seems to be a known "bug"... You should unexport all the pins at the end of the application, either calling .Unexport() or .Dispose()

**Comment by ninjaboy** [comment]
Otherwise just restart the device?

On Mon, Mar 30, 2015 at 8:14 PM, Alex notifications@github.com wrote:

> It seems to be a known "bug"... You should unexport all the pins at the
> end of the application, either calling .Unexport() or .Dispose()
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/AlexSartori/Raspberry-GPIO-Manager/issues/1#issuecomment-87795905
> .

## 

With best regards,
_Alexey Stolybko_
