### ISSUE TITLE
Does the GPIOManger drive can be used in one-wire protocol?

### ISSUE THREAD

**Issue by wxtripoder** [AlexSartori/Raspberry-GPIO-Manager#8]
Hi Alex, 
Does the GPIOManger drive can be used in one-wire protocol?
For example, does the GPIOManger drive can be used to read the sensor named "DHT11" value?
If can, how to read? thanks;

**Comment by AlexSartori** [comment]
No I'm sorry, that's a whole different protocol. As of now this library only supports switching outputs on and off and reading inputs' values.
I've been hoping to integrate more for a while, but I'm struggling to find the time lately.. :)
